# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: simakstmikbdgbali CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.6.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}    

      
    - name: upload ke ftp server stmik bandung bali
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.server}}
        username: ${{ secrets.username}}
        password: ${{ secrets.password}}
        port: 21
        protocol: ftp
        local_dir: ./frontend/dist/
        remote_dir:  /home/stmikba1/public_html/simak/
        args: --delete # will delete files on the server if you've deleted them in git
        exclude: '[.git*, .git*/**, **/.git*/**, backend*/**, frontend/src/**, frontend/public*/**]'
