# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: simakstmikbdgbali CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.6.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}    

      
    - name: upload ke ftp server stmik bandung bali
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        FTP_SERVER: ftp.myhosing.com
        FTP_USERNAME: myusername
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: ./public/
        REMOTE_DIR:  /path/to/site/root/on/my/hosting/
        ARGS: --delete # will delete files on the server if you've deleted them in git
